data:
 datasetPath: "spotify_dataset.csv"
constant:
  danceability_str: "danceability"
  energy_str: "energy"
  loudness_str: "loudness"
  speechiness_str: "speechiness"
  acousticness_str: "acousticness"
  instrumentallness_str: "instrumentalness"
  liveness_str: "liveness"
  popularity_str: "popularity"
  valence_str: "valence"
  tempo_str: "tempo"
  duration_str: "duration_ms"
  timesignature_str: "time_signature"
  key_str: "key"
  mode_str: "mode"

  # Cat columns
  track_id_str: "track_id"
  artists_str: "artists"
  album_name_str: "album_name"
  track_name_str: "track_name"
  explicit_str: "explicit"
  track_genre_str: "track_genre"
# For Main.py
cmd:
  # Supported Model
  dt: 'decision_tree'
  rf: 'random_forest' 
  knn: 'k_nearest_neighbors'
  ada_bst: 'ada_boost'
  lin_reg: 'linear_regression'
  lgbm: "light_gbm"
  xgboost: "xgboost"

  # Supported Target
  dance: "danceability"
  energy: "energy"
  loud: "loudness"
  speech: "speechiness"
  acoustic: "acousticness"
  instrumental: "instrumentalness"
  live: "liveness"
  popularity: "popularity"
  valence: "valence"
  tempo: "tempo"
  duration: "duration_ms"

ms_split:
  random_state: 0
  test_size: 0.2

knn_args:
  n_neighbors: 500
  weights: "distance"

linreg_args: 
  n_jobs: -1

ada_args: 
  n_estimators: 100
  lr: 1.0
  loss: "square"
  random_state: 1

dt_args:
  min_leaf: 25
  min_split: 25
  max_depth: 12

rf_args:
  n_estimator: 100
  min_leaf: 5
  min_split: 5
  max_depth: 12

lg_args:
  objective: "rmse"
  learning_rate: 0.1
  reg_lambda: 1.0
  reg_alpha: 0.1
  max_depth: 5
  n_estimators: 10000
  colsample_bytree: .5
  min_child_samples: 10
  subsample_freq: 3
  subsample: 0.9
  importance_type: 'gain'
  random_state: 71
  num_leaves: 62
mlp_args:
  in_features: 12
  lr: 0.001
  epoch: 50
  default_features: 500

mlflow:
  mse_train: "mse_train"
  mse_val: "mse_val"
  rmse_train: "rmse_train"
  rmse_val: "rmse_val"
